from __future__ import annotations

RANDOM_STATE = 42
DEFAULT_TEST_SIZE = 0.20
DEFAULT_CV = 5
DEFAULT_MIN_SAMPLES = 30
DEFAULT_ALPHA = 1.0
DEFAULT_CORRELATION_THRESHOLD = 0.95
DEFAULT_PERMUTATION_REPEATS = 8
DEFAULT_DIVISION_PRIOR = 20.0